function Resume () {
    return (
        <>
        <section className='border-b-2 flex flex-start flex-col text-left'>
            <h1 className='mt-10 ml-10 font-semibold text-2xl p-3'>Resume</h1>
            <h5 className='ml-10 py-4 px-3'>Download a copy <a href="https://docs.google.com/document/d/1oGnuK0qlJaKSEy8ad6PwSijSmbz_-Y4PuhU6mxaBIyQ/edit?usp=sharing" target="_blank" className='text-red-900 font-bold'>here</a></h5>
        </section>
            <div className='flex flex-col items-center my-6'>
                <h3 className='font-semibold text-xl mt-10'>Summary</h3>
                <p className='p-4 w-4/5'>
                    Skilled full-stack software engineer with an extensive background in pharmaceutical compounding.
                    Methodical problem solver with expert judgment and insightful decision making.
                    Excels in rapidly analyzing and troubleshooting complex scenarios while adhering to rigorous
                    quality standards and maximizing productivity in meeting consumer demand.
                    Eager to utilize my expertise and ingenuity to enhance user experiences by applying my passion
                    for innovation and simplicity.
                </p>
            </div>
            <div className='text-left ml-20 my-10'>
                <h3 className='font-semibold text-xl py-3'>Technical Skills</h3>
                <ul className='py-3 resume-list'>
                    <li><strong>Languages:</strong> JavaScript, React, HTML5, CSS3</li>
                    <li><strong>Frameworks / Libraries: </strong>React, Express, Next.js</li>
                    <li><strong>Databases / Backends: </strong>MongoDB, PostgreSQL, Firebase, AWS</li>
                    <li><strong>Methodologies: </strong>MVC, Restful Architecture</li>
                    <li><strong>Tools: </strong>Git, VS Code, Postman</li>
                </ul>
            </div>
            <div className='text-left ml-20 my-10'>
                <h3 className='font-semibold text-xl'>Work Experience</h3>
                <ul>Mixlab Inc.
                    <li>
                        <strong>Hazardous Drug Lead Compounding Technician</strong> Feb 2023 - Present
                    </li>
                    <li>
                        <i>Senior Compounding Technician</i> Nov 2021 - Feb 2023
                    </li>
                    <li>
                        <i>Pharmacy Technician</i> Jan 2020 - Nov 2021
                    </li>
                </ul>
                <ul>
                    <li>Oversee a team of 8 in established hazardous drug handling and compounding principles as defined by federal requirements and standard operating procedures.</li>
                    <li>Collaborate with management to improve workflow efficiency by reducing human errors, while monitoring quality compliance on a daily basis to reduce hazardous exposure.</li>
                    <li>Train over 10 team members on specific compounding techniques, formulation calculations, and pharmaceutical data entry.</li>
                    <li>Manage cross-functional team members to streamline workflow by delegating tasks, while adapting to ongoing demands and providing solutions to optimize standard operating procedures.</li>
                    <li>Analyze the unique demands of each compound and refine compounding techniques accordingly, yielding 14-18 high quality preparations on a daily basis.</li>
                    <li>Produce 1/3 total daily pharmacy script volume generated by a team of 6, by processing 80-100 scripts with near 100% accuracy. </li>
                </ul>
            </div>
            <div>
                <h3 className='font-semibold text-xl'>Education</h3>
                <ul className='flex flex-col'>
                    <li><strong>General Assembly</strong> -  Nov 2022 - May 2023
                    <p><i className='mr-auto'>Software Engineering Fellow</i></p></li>
                    <li><strong>Hunter College</strong> <i>Bachelor's of Arts in Chemistry</i> Expected Date of Graduation: June 2026</li>
                </ul>
            </div>
        </>
    );
}


export default Resume;